import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';

// The data structure our form will submit
interface IssueFormData {
  description: string;
}

// Props the componenzzt expects
interface IssueFormProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  addIssue: (data: any) => Promise<void>;
  issue?: any; 
}

export const IssueForm = ({ open, onOpenChange, issue, addIssue }: IssueFormProps) => {
  const { user } = useAuth(); // Get user info to send to backend
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState<IssueFormData>({
    description: '',
  });

  // This useEffect will reset the form when it opens
  useEffect(() => {
    if (open) {
      setFormData({ description: '' });
    }
  }, [open]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      toast.error("You must be logged in to create an issue.");
      return;
    }
    setLoading(true);

    try {
      // Construct the final data object for the backend
      // Only send: description, roomNumber, createdBy
      // Title and category will be auto-generated by backend ML model
      const issuePayload = {
        description: formData.description,
        roomNumber: user.roomNo || 'N/A',
        createdBy: user.name,
      };
      
      await addIssue(issuePayload);
      onOpenChange(false); // Close the modal on success
    } catch (error) {
      toast.error("Failed to submit issue.");
      console.error(error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>{issue ? 'Edit Issue' : 'Raise New Issue'}</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} id="issue-form" className="space-y-4">
          <div>
            <Label htmlFor="description">Describe Your Issue</Label>
            <Textarea
              id="description"
              value={formData.description}
              onChange={(e) => setFormData({ ...formData, description: e.target.value })}
              placeholder="Please describe the issue in detail. The category will be automatically determined based on your description."
              rows={6}
              required
              className="min-h-[120px]"
            />
            <p className="text-sm text-muted-foreground mt-2">
              Example: "Water leaking from the washroom pipe in room 101"
            </p>
          </div>
        </form>
        <DialogFooter>
          <Button type="button" variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button type="submit" form="issue-form" disabled={loading}>
            {loading ? 'Submitting...' : 'Submit Issue'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};